### ISSUE TITLE
Please advertise the way to file bugs

### ISSUE THREAD

**Issue by setharnold** [canonical/discourse-k8s-operator#160]
### Bug Description

Hello, it's not obvious how to report bugs and problems with the various Canonical and Ubuntu discourse sites.

- The "contact us" section at the end of https://discourse.canonical.com/about just says to contact https://canonical.com. It should be an email address or a link to a web-accessible form that feeds into a ticketing tool or something similar.

- The FAQ https://discourse.canonical.com/faq#power says that there's a site feedback category https://discourse.canonical.com/c/site-feedback but that returns a 404.

### To Reproduce

N/A

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by cbartz** [comment]
@alithethird Can you have a look please?

**Comment by alithethird** [comment]
Hi! We do not manage any Discourse sites. We only develop the charm. To file bugs about specific sites you need to contact Canonical IS.
