### ISSUE TITLE
Please add a charm action to run the upload_assets console command

### ISSUE THREAD

**Issue by barryprice** [canonical/discourse-k8s-operator#209]
### Enhancement Proposal

Hi

It's possible for a charmed deploy using S3 integration to enter a state where the generated HTML references S3-hosted files that don't exist - see #208.

Currently the least painful workaround is to get a discourse console session on a pod, and run `bundle exec rails s3:upload_assets`.

This enhancement proposal is a request for a charm action to perform the above, and ideally to confirm a successful upload.

**Comment by cbartz** [comment]
@javierdelapuente Please have a look and create a ticket in the backlog if necessary.

**Comment by cbartz** [comment]
Closing, @barryprice , please comment if this is still necessary.
