### ISSUE TITLE
Update to nginx-route for Ingress

### ISSUE THREAD

**Issue by merkata** [canonical/discourse-k8s-operator#65]
### Enhancement Proposal

Currently the charm supports the nginx-integrator `ingress` relation, which is deprecated in favor of the `nginx-route` library and interface. It would be good to update to the nginx-route relation (and update the docs) to avoid users being presented with a deprecated notice.

**Comment by nrobinaubertin** [comment]
Closed with https://github.com/canonical/discourse-k8s-operator/pull/69
